export type CourseLevel = "Beginner" | "Intermediate" | "Advanced";

export type CourseCategory =
  | "Action"
  | "Adventure"
  | "Biography"
  | "Crime"
  | "Drama"
  | "Fantasy"
  | "Horror"
  | "Mystery"
  | "Sci-Fi"
  | "Thriller"
  | "War";

export interface Course {
  id: string;
  slug: string;
  title: string;
  image: string;
  shortDescription: string;
  description: string;
  category: CourseCategory;
  level: CourseLevel;
  duration: string;
  imdbRating: number;
  language: string;
  country: string;
  boxOffice: string;
  instructorSlug: string;
  lessons: string[];
}

export interface Instructor {
  id: string;
  slug: string;
  name: string;
  image: string;
  specialty: string;
  shortBio: string;
  bio: string;
}

export const instructors: Instructor[] = [
  {
    id: "i1",
    slug: "christopher-nolan",
    name: "Christopher Nolan",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg",
    specialty: "Director",
    shortBio: "British-American filmmaker known for ambitious, visually striking films.",
    bio: "Christopher Nolan is known for large-scale stories, nonlinear structure, practical spectacle, and films that mix emotion with complex ideas.",
  },
  {
    id: "i2",
    slug: "steven-spielberg",
    name: "Steven Spielberg",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg",
    specialty: "Director",
    shortBio: "One of the most influential directors in modern cinema.",
    bio: "Steven Spielberg is known for adventure, drama, science fiction, historical films, and emotionally powerful blockbuster storytelling.",
  },
  {
    id: "i3",
    slug: "quentin-tarantino",
    name: "Quentin Tarantino",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg",
    specialty: "Director",
    shortBio: "American filmmaker known for stylized dialogue and nonlinear storytelling.",
    bio: "Quentin Tarantino is known for sharp dialogue, crime stories, genre references, memorable characters, and bold narrative structure.",
  },
  {
    id: "i4",
    slug: "martin-scorsese",
    name: "Martin Scorsese",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/9U9Y5GQuWX3EZy39B8nkk4NY01S.jpg",
    specialty: "Director",
    shortBio: "Legendary American director known for crime dramas and character studies.",
    bio: "Martin Scorsese is one of cinema's most respected filmmakers, known for intense character studies, crime stories, faith, guilt, and ambition.",
  },
  {
    id: "i5",
    slug: "david-fincher",
    name: "David Fincher",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/tpEczFclQZeKAiCeKZZ0adRvtfz.jpg",
    specialty: "Director",
    shortBio: "American filmmaker known for dark thrillers and precise visual style.",
    bio: "David Fincher is known for meticulous direction, psychological tension, mystery, obsession, and dark modern thrillers.",
  },
  {
    id: "i6",
    slug: "denis-villeneuve",
    name: "Denis Villeneuve",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/zdDx9Xs93UIrJFWYApYR28J8M6b.jpg",
    specialty: "Director",
    shortBio: "Canadian filmmaker known for atmospheric, visually powerful cinema.",
    bio: "Denis Villeneuve is known for precise visual storytelling, atmospheric tension, science fiction, thrillers, and monumental cinematic worlds.",
  },
  {
    id: "i7",
    slug: "ridley-scott",
    name: "Ridley Scott",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/97SO7H0UlS3racqjeW5JTy8c6GM.jpg",
    specialty: "Director",
    shortBio: "British filmmaker known for epic, science-fiction, and historical films.",
    bio: "Ridley Scott is known for strong visual style, science fiction classics, historical epics, and large-scale cinematic worlds.",
  },
  {
    id: "i8",
    slug: "james-cameron",
    name: "James Cameron",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/9NAZnTjBQ9WcXAQEzZpKy4vdQto.jpg",
    specialty: "Director",
    shortBio: "Canadian filmmaker known for blockbuster scale and technical innovation.",
    bio: "James Cameron is known for science fiction, action, epic spectacle, groundbreaking visual effects, and some of the highest-grossing films ever made.",
  },
  {
    id: "i9",
    slug: "peter-jackson",
    name: "Peter Jackson",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/bNc908d59Ba8VDNr4eCcm4G1cR.jpg",
    specialty: "Director",
    shortBio: "New Zealand filmmaker known for fantasy epics and large-scale adventures.",
    bio: "Peter Jackson is best known for The Lord of the Rings and The Hobbit films, combining fantasy, adventure, visual effects, and emotional storytelling.",
  },
  {
    id: "i10",
    slug: "francis-ford-coppola",
    name: "Francis Ford Coppola",
    image: "https://media.themoviedb.org/t/p/w300_and_h450_face/IwGgkmW6IoJ9vuNF0T9CU3FYUX.jpg",
    specialty: "Director",
    shortBio: "Legendary American filmmaker best known for The Godfather trilogy.",
    bio: "Francis Ford Coppola is one of the defining filmmakers of New Hollywood, known for crime epics, war films, intimate drama, and operatic storytelling.",
  },
];

export const courses: Course[] = [
  {
    id: "c1",
    slug: "the-dark-knight-2008",
    title: "The Dark Knight (2008)",
    image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    shortDescription: "Batman faces the Joker, a criminal mastermind who wants to throw Gotham into chaos.",
    description: "Batman joins forces with Gordon and Harvey Dent to fight organized crime, but the Joker pushes Gotham and its heroes to their moral limits.",
    category: "Action",
    level: "Beginner",
    duration: "2h 32m",
    imdbRating: 9.0,
    language: "English",
    country: "United States / United Kingdom",
    boxOffice: "$1.006B worldwide",
    instructorSlug: "christopher-nolan",
    lessons: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"],
  },
  {
    id: "c2",
    slug: "inception-2010",
    title: "Inception (2010)",
    image: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    shortDescription: "A skilled thief enters dreams to steal secrets and plant ideas.",
    description: "Dom Cobb is offered a chance to erase his past crimes if he can perform inception: planting an idea inside someone's mind.",
    category: "Sci-Fi",
    level: "Advanced",
    duration: "2h 28m",
    imdbRating: 8.8,
    language: "English",
    country: "United States / United Kingdom",
    boxOffice: "$839M worldwide",
    instructorSlug: "christopher-nolan",
    lessons: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Marion Cotillard"],
  },
  {
    id: "c3",
    slug: "interstellar-2014",
    title: "Interstellar (2014)",
    image: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    shortDescription: "Explorers travel through a wormhole to find humanity a new home.",
    description: "A father leaves Earth on a dangerous space mission to search for a future for humanity while time separates him from his children.",
    category: "Sci-Fi",
    level: "Intermediate",
    duration: "2h 49m",
    imdbRating: 8.7,
    language: "English",
    country: "United States / United Kingdom / Canada",
    boxOffice: "$733M worldwide",
    instructorSlug: "christopher-nolan",
    lessons: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
  },
  {
    id: "c4",
    slug: "dunkirk-2017",
    title: "Dunkirk (2017)",
    image: "https://image.tmdb.org/t/p/w500/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
    shortDescription: "Allied soldiers are trapped and evacuated during World War II.",
    description: "Dunkirk tells the evacuation story from land, sea, and air as soldiers and civilians fight against time to survive.",
    category: "War",
    level: "Intermediate",
    duration: "1h 46m",
    imdbRating: 7.8,
    language: "English",
    country: "United Kingdom / United States / France",
    boxOffice: "$527M worldwide",
    instructorSlug: "christopher-nolan",
    lessons: ["Fionn Whitehead", "Tom Hardy", "Mark Rylance", "Kenneth Branagh", "Cillian Murphy"],
  },
  {
    id: "c5",
    slug: "oppenheimer-2023",
    title: "Oppenheimer (2023)",
    image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    shortDescription: "The story of J. Robert Oppenheimer and the creation of the atomic bomb.",
    description: "The film follows Oppenheimer's role in the Manhattan Project and the political, personal, and moral consequences that followed.",
    category: "Biography",
    level: "Intermediate",
    duration: "3h 00m",
    imdbRating: 8.3,
    language: "English",
    country: "United States / United Kingdom",
    boxOffice: "$976M worldwide",
    instructorSlug: "christopher-nolan",
    lessons: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
  },
  {
    id: "c6",
    slug: "jaws-1975",
    title: "Jaws (1975)",
    image: "https://image.tmdb.org/t/p/w500/lxM6kqilAdpdhqUl2biYp5frUxE.jpg",
    shortDescription: "A seaside town is terrorized by a great white shark.",
    description: "A police chief, a scientist, and a shark hunter set out to stop a deadly shark threatening a summer resort town.",
    category: "Thriller",
    level: "Beginner",
    duration: "2h 04m",
    imdbRating: 8.1,
    language: "English",
    country: "United States",
    boxOffice: "$476M worldwide",
    instructorSlug: "steven-spielberg",
    lessons: ["Roy Scheider", "Robert Shaw", "Richard Dreyfuss", "Lorraine Gary", "Murray Hamilton"],
  },
  {
    id: "c7",
    slug: "raiders-of-the-lost-ark-1981",
    title: "Raiders of the Lost Ark (1981)",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/ceG9VzoRAVGwivFU403Wc3AHRys.jpg",
    shortDescription: "Indiana Jones races to find the Ark of the Covenant.",
    description: "Archaeologist Indiana Jones faces dangerous enemies while searching for a legendary biblical artifact.",
    category: "Adventure",
    level: "Beginner",
    duration: "1h 55m",
    imdbRating: 8.4,
    language: "English",
    country: "United States",
    boxOffice: "$390M worldwide",
    instructorSlug: "steven-spielberg",
    lessons: ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies", "Denholm Elliott"],
  },
  {
    id: "c8",
    slug: "et-the-extra-terrestrial-1982",
    title: "E.T. the Extra-Terrestrial (1982)",
    image: "https://image.tmdb.org/t/p/w500/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg",
    shortDescription: "A lonely boy befriends a gentle alien stranded on Earth.",
    description: "Elliott discovers and protects a lost alien while trying to help him return home.",
    category: "Sci-Fi",
    level: "Beginner",
    duration: "1h 55m",
    imdbRating: 7.9,
    language: "English",
    country: "United States",
    boxOffice: "$793M worldwide",
    instructorSlug: "steven-spielberg",
    lessons: ["Henry Thomas", "Drew Barrymore", "Dee Wallace", "Peter Coyote", "Robert MacNaughton"],
  },
  {
    id: "c9",
    slug: "jurassic-park-1993",
    title: "Jurassic Park (1993)",
    image: "https://image.tmdb.org/t/p/w500/fjTU1Bgh3KJu4aatZil3sofR2zC.jpg",
    shortDescription: "A dinosaur theme park turns into a survival nightmare.",
    description: "Scientists and visitors fight for survival when genetically recreated dinosaurs escape control inside a theme park.",
    category: "Adventure",
    level: "Intermediate",
    duration: "2h 07m",
    imdbRating: 8.2,
    language: "English",
    country: "United States",
    boxOffice: "$1.109B worldwide",
    instructorSlug: "steven-spielberg",
    lessons: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough", "Bob Peck"],
  },
  {
    id: "c10",
    slug: "saving-private-ryan-1998",
    title: "Saving Private Ryan (1998)",
    image: "https://image.tmdb.org/t/p/w500/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
    shortDescription: "A group of soldiers searches for one man during World War II.",
    description: "After D-Day, a small unit is sent behind enemy lines to bring home the last surviving brother of a family.",
    category: "War",
    level: "Advanced",
    duration: "2h 49m",
    imdbRating: 8.6,
    language: "English",
    country: "United States",
    boxOffice: "$482M worldwide",
    instructorSlug: "steven-spielberg",
    lessons: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns", "Barry Pepper"],
  },
  {
    id: "c11",
    slug: "reservoir-dogs-1992",
    title: "Reservoir Dogs (1992)",
    image: "https://image.tmdb.org/t/p/w500/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
    shortDescription: "A botched robbery turns criminals against each other.",
    description: "After a jewelry heist goes wrong, surviving criminals suspect one of them is an undercover police officer.",
    category: "Crime",
    level: "Advanced",
    duration: "1h 39m",
    imdbRating: 8.3,
    language: "English",
    country: "United States",
    boxOffice: "$2.9M worldwide",
    instructorSlug: "quentin-tarantino",
    lessons: ["Harvey Keitel", "Tim Roth", "Michael Madsen", "Steve Buscemi", "Chris Penn"],
  },
  {
    id: "c12",
    slug: "pulp-fiction-1994",
    title: "Pulp Fiction (1994)",
    image: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    shortDescription: "Interconnected crime stories unfold in Los Angeles.",
    description: "Hitmen, a boxer, a gangster's wife, and criminals collide in a nonlinear story of crime, chance, and consequences.",
    category: "Crime",
    level: "Advanced",
    duration: "2h 34m",
    imdbRating: 8.9,
    language: "English",
    country: "United States",
    boxOffice: "$214M worldwide",
    instructorSlug: "quentin-tarantino",
    lessons: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis", "Ving Rhames"],
  },
  {
    id: "c13",
    slug: "kill-bill-volume-1-2003",
    title: "Kill Bill: Volume 1 (2003)",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg",
    shortDescription: "A former assassin begins a violent revenge mission.",
    description: "The Bride awakens from a coma and hunts the former allies who betrayed her.",
    category: "Action",
    level: "Advanced",
    duration: "1h 51m",
    imdbRating: 8.2,
    language: "English / Japanese",
    country: "United States",
    boxOffice: "$181M worldwide",
    instructorSlug: "quentin-tarantino",
    lessons: ["Uma Thurman", "Lucy Liu", "Vivica A. Fox", "Daryl Hannah", "David Carradine"],
  },
  {
    id: "c14",
    slug: "inglourious-basterds-2009",
    title: "Inglourious Basterds (2009)",
    image: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    shortDescription: "A revenge plot unfolds in Nazi-occupied France.",
    description: "A group of Jewish-American soldiers and a cinema owner become part of a plan to strike against Nazi leaders.",
    category: "War",
    level: "Advanced",
    duration: "2h 33m",
    imdbRating: 8.4,
    language: "English / German / French / Italian",
    country: "United States / Germany",
    boxOffice: "$321M worldwide",
    instructorSlug: "quentin-tarantino",
    lessons: ["Brad Pitt", "Christoph Waltz", "Mélanie Laurent", "Diane Kruger", "Eli Roth"],
  },
  {
    id: "c15",
    slug: "django-unchained-2012",
    title: "Django Unchained (2012)",
    image: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    shortDescription: "A freed man becomes a bounty hunter and searches for his wife.",
    description: "Django teams up with a German bounty hunter to rescue his wife from a brutal plantation owner.",
    category: "Drama",
    level: "Advanced",
    duration: "2h 45m",
    imdbRating: 8.5,
    language: "English / German / French",
    country: "United States",
    boxOffice: "$426M worldwide",
    instructorSlug: "quentin-tarantino",
    lessons: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington", "Samuel L. Jackson"],
  },
  {
    id: "c16",
    slug: "taxi-driver-1976",
    title: "Taxi Driver (1976)",
    image: "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
    shortDescription: "A lonely taxi driver descends into obsession and violence.",
    description: "Travis Bickle moves through a decaying New York City while his isolation and anger grow dangerous.",
    category: "Drama",
    level: "Advanced",
    duration: "1h 54m",
    imdbRating: 8.2,
    language: "English",
    country: "United States",
    boxOffice: "$28M worldwide",
    instructorSlug: "martin-scorsese",
    lessons: ["Robert De Niro", "Jodie Foster", "Cybill Shepherd", "Harvey Keitel", "Peter Boyle"],
  },
  {
    id: "c17",
    slug: "raging-bull-1980",
    title: "Raging Bull (1980)",
    image: "https://image.tmdb.org/t/p/w500/rEviyDWNbAFmvvCPlkMRPAGUElG.jpg",
    shortDescription: "A boxer battles success, jealousy, and self-destruction.",
    description: "The film follows Jake LaMotta's rise and personal collapse inside and outside the boxing ring.",
    category: "Biography",
    level: "Advanced",
    duration: "2h 09m",
    imdbRating: 8.1,
    language: "English",
    country: "United States",
    boxOffice: "$23M worldwide",
    instructorSlug: "martin-scorsese",
    lessons: ["Robert De Niro", "Cathy Moriarty", "Joe Pesci", "Frank Vincent", "Nicholas Colasanto"],
  },
  {
    id: "c18",
    slug: "goodfellas-1990",
    title: "Goodfellas (1990)",
    image: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    shortDescription: "The rise and fall of a mob associate inside organized crime.",
    description: "Henry Hill becomes involved with the mob and experiences the attraction, danger, and destruction of organized crime.",
    category: "Crime",
    level: "Advanced",
    duration: "2h 26m",
    imdbRating: 8.7,
    language: "English / Italian",
    country: "United States",
    boxOffice: "$47M worldwide",
    instructorSlug: "martin-scorsese",
    lessons: ["Ray Liotta", "Robert De Niro", "Joe Pesci", "Lorraine Bracco", "Paul Sorvino"],
  },
  {
    id: "c19",
    slug: "the-departed-2006",
    title: "The Departed (2006)",
    image: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    shortDescription: "An undercover cop and a police mole try to expose each other.",
    description: "Two men on opposite sides of the law become trapped in a dangerous game of identity, loyalty, and betrayal.",
    category: "Crime",
    level: "Advanced",
    duration: "2h 31m",
    imdbRating: 8.5,
    language: "English",
    country: "United States / Hong Kong",
    boxOffice: "$292M worldwide",
    instructorSlug: "martin-scorsese",
    lessons: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg", "Martin Sheen"],
  },
  {
    id: "c20",
    slug: "the-wolf-of-wall-street-2013",
    title: "The Wolf of Wall Street (2013)",
    image: "https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
    shortDescription: "A stockbroker rises through greed, fraud, and excess.",
    description: "Jordan Belfort builds a financial empire through manipulation and excess before consequences catch up with him.",
    category: "Biography",
    level: "Advanced",
    duration: "3h 00m",
    imdbRating: 8.2,
    language: "English / French",
    country: "United States",
    boxOffice: "$407M worldwide",
    instructorSlug: "martin-scorsese",
    lessons: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey", "Kyle Chandler"],
  },
  {
    id: "c21",
    slug: "se7en-1995",
    title: "Se7en (1995)",
    image: "https://image.tmdb.org/t/p/w500/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    shortDescription: "Two detectives hunt a killer inspired by the seven deadly sins.",
    description: "Detectives Somerset and Mills investigate a dark series of murders connected to sin, punishment, and obsession.",
    category: "Thriller",
    level: "Advanced",
    duration: "2h 07m",
    imdbRating: 8.6,
    language: "English",
    country: "United States",
    boxOffice: "$327M worldwide",
    instructorSlug: "david-fincher",
    lessons: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey", "R. Lee Ermey"],
  },
  {
    id: "c22",
    slug: "fight-club-1999",
    title: "Fight Club (1999)",
    image: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    shortDescription: "An office worker and a soap maker create an underground fight club.",
    description: "A dissatisfied man forms a strange friendship that grows into an underground movement with dangerous consequences.",
    category: "Drama",
    level: "Advanced",
    duration: "2h 19m",
    imdbRating: 8.8,
    language: "English",
    country: "United States / Germany",
    boxOffice: "$101M worldwide",
    instructorSlug: "david-fincher",
    lessons: ["Edward Norton", "Brad Pitt", "Helena Bonham Carter", "Meat Loaf", "Jared Leto"],
  },
  {
    id: "c23",
    slug: "zodiac-2007",
    title: "Zodiac (2007)",
    image: "https://image.tmdb.org/t/p/w500/6YmeO4pB7XTh8P8F960O1uA14JO.jpg",
    shortDescription: "Reporters and investigators search for the Zodiac Killer.",
    description: "A cartoonist, journalists, and detectives become consumed by the long investigation into the Zodiac murders.",
    category: "Mystery",
    level: "Advanced",
    duration: "2h 37m",
    imdbRating: 7.7,
    language: "English",
    country: "United States",
    boxOffice: "$85M worldwide",
    instructorSlug: "david-fincher",
    lessons: ["Jake Gyllenhaal", "Mark Ruffalo", "Robert Downey Jr.", "Anthony Edwards", "Brian Cox"],
  },
  {
    id: "c24",
    slug: "the-social-network-2010",
    title: "The Social Network (2010)",
    image: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    shortDescription: "The founding of Facebook becomes a story of ambition and betrayal.",
    description: "Mark Zuckerberg creates Facebook while friendships, lawsuits, and power struggles shape the rise of a tech empire.",
    category: "Biography",
    level: "Intermediate",
    duration: "2h 00m",
    imdbRating: 7.8,
    language: "English",
    country: "United States",
    boxOffice: "$225M worldwide",
    instructorSlug: "david-fincher",
    lessons: ["Jesse Eisenberg", "Andrew Garfield", "Justin Timberlake", "Armie Hammer", "Rooney Mara"],
  },
  {
    id: "c25",
    slug: "gone-girl-2014",
    title: "Gone Girl (2014)",
    image: "https://image.tmdb.org/t/p/w500/wOwI8IfgkT4o7gKgohYa5IBpJUj.jpg",
    shortDescription: "A missing woman case exposes a marriage full of secrets.",
    description: "When Amy Dunne disappears, her husband becomes the center of a media storm and a disturbing mystery.",
    category: "Thriller",
    level: "Advanced",
    duration: "2h 29m",
    imdbRating: 8.1,
    language: "English",
    country: "United States",
    boxOffice: "$369M worldwide",
    instructorSlug: "david-fincher",
    lessons: ["Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "Tyler Perry", "Carrie Coon"],
  },
  {
    id: "c26",
    slug: "prisoners-2013",
    title: "Prisoners (2013)",
    image: "https://image.tmdb.org/t/p/w500/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    shortDescription: "A father searches desperately for his missing daughter.",
    description: "After two girls disappear, a father and detective follow different paths through a dark and morally difficult investigation.",
    category: "Thriller",
    level: "Advanced",
    duration: "2h 33m",
    imdbRating: 8.2,
    language: "English",
    country: "United States",
    boxOffice: "$122M worldwide",
    instructorSlug: "denis-villeneuve",
    lessons: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello", "Paul Dano"],
  },
  {
    id: "c27",
    slug: "sicario-2015",
    title: "Sicario (2015)",
    image: "https://image.tmdb.org/t/p/w500/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg",
    shortDescription: "An FBI agent enters a dangerous drug-war operation.",
    description: "An idealistic agent joins a covert task force and confronts the brutal moral reality of the border drug war.",
    category: "Thriller",
    level: "Advanced",
    duration: "2h 01m",
    imdbRating: 7.7,
    language: "English / Spanish",
    country: "United States / Mexico / Hong Kong",
    boxOffice: "$85M worldwide",
    instructorSlug: "denis-villeneuve",
    lessons: ["Emily Blunt", "Benicio del Toro", "Josh Brolin", "Daniel Kaluuya", "Jon Bernthal"],
  },
  {
    id: "c28",
    slug: "arrival-2016",
    title: "Arrival (2016)",
    image: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    shortDescription: "A linguist tries to communicate with mysterious alien visitors.",
    description: "When alien spacecraft appear around the world, a linguist must decode their language before global fear turns into conflict.",
    category: "Sci-Fi",
    level: "Intermediate",
    duration: "1h 56m",
    imdbRating: 7.9,
    language: "English / Russian / Mandarin",
    country: "United States / Canada",
    boxOffice: "$203M worldwide",
    instructorSlug: "denis-villeneuve",
    lessons: ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg", "Tzi Ma"],
  },
  {
    id: "c29",
    slug: "blade-runner-2049-2017",
    title: "Blade Runner 2049 (2017)",
    image: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    shortDescription: "A young blade runner uncovers a secret that could change society.",
    description: "Officer K discovers a buried secret that leads him to former blade runner Rick Deckard and questions of memory and identity.",
    category: "Sci-Fi",
    level: "Advanced",
    duration: "2h 44m",
    imdbRating: 8.0,
    language: "English / Finnish / Japanese / Hungarian / Russian / Spanish",
    country: "United States / United Kingdom / Canada / Spain",
    boxOffice: "$268M worldwide",
    instructorSlug: "denis-villeneuve",
    lessons: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Robin Wright", "Jared Leto"],
  },
  {
    id: "c30",
    slug: "dune-part-two-2024",
    title: "Dune: Part Two (2024)",
    image: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    shortDescription: "Paul Atreides continues his journey among the Fremen.",
    description: "Paul joins the Fremen, seeks revenge, and struggles with visions of power, war, and destiny.",
    category: "Sci-Fi",
    level: "Advanced",
    duration: "2h 46m",
    imdbRating: 8.5,
    language: "English",
    country: "United States / Canada",
    boxOffice: "$714M worldwide",
    instructorSlug: "denis-villeneuve",
    lessons: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler"],
  },
  {
    id: "c31",
    slug: "alien-1979",
    title: "Alien (1979)",
    image: "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
    shortDescription: "A spaceship crew is hunted by a deadly alien creature.",
    description: "The crew of the Nostromo responds to a signal and brings aboard a terrifying lifeform.",
    category: "Horror",
    level: "Advanced",
    duration: "1h 57m",
    imdbRating: 8.5,
    language: "English",
    country: "United Kingdom / United States",
    boxOffice: "$185M worldwide",
    instructorSlug: "ridley-scott",
    lessons: ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Ian Holm", "Veronica Cartwright"],
  },
  {
    id: "c32",
    slug: "blade-runner-1982",
    title: "Blade Runner (1982)",
    image: "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    shortDescription: "A blade runner hunts artificial humans in a dystopian future.",
    description: "Rick Deckard is sent to track down replicants while questions of identity and humanity blur the line between man and machine.",
    category: "Sci-Fi",
    level: "Advanced",
    duration: "1h 57m",
    imdbRating: 8.1,
    language: "English / German / Cantonese / Japanese / Hungarian",
    country: "United States / Hong Kong / United Kingdom",
    boxOffice: "$42M worldwide",
    instructorSlug: "ridley-scott",
    lessons: ["Harrison Ford", "Rutger Hauer", "Sean Young", "Edward James Olmos", "Daryl Hannah"],
  },
  {
    id: "c33",
    slug: "gladiator-2000",
    title: "Gladiator (2000)",
    image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    shortDescription: "A betrayed Roman general becomes a gladiator and seeks justice.",
    description: "Maximus is forced into slavery and rises in the arena while seeking revenge against the emperor who destroyed his life.",
    category: "Action",
    level: "Intermediate",
    duration: "2h 35m",
    imdbRating: 8.5,
    language: "English",
    country: "United States / United Kingdom / Malta / Morocco",
    boxOffice: "$465M worldwide",
    instructorSlug: "ridley-scott",
    lessons: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed", "Djimon Hounsou"],
  },
  {
    id: "c34",
    slug: "kingdom-of-heaven-2005",
    title: "Kingdom of Heaven (2005)",
    image: "https://image.tmdb.org/t/p/w500/uk55nBEFIQFveIiy9jvLGiVtk4h.jpg",
    shortDescription: "A blacksmith becomes a knight during the Crusades.",
    description: "Balian travels to Jerusalem and becomes involved in war, faith, politics, and the defense of a fragile kingdom.",
    category: "War",
    level: "Advanced",
    duration: "2h 24m",
    imdbRating: 7.3,
    language: "English / Arabic / Latin / Italian",
    country: "United States / United Kingdom / Germany / Spain / Morocco",
    boxOffice: "$218M worldwide",
    instructorSlug: "ridley-scott",
    lessons: ["Orlando Bloom", "Eva Green", "Liam Neeson", "Jeremy Irons", "Ghassan Massoud"],
  },
  {
    id: "c35",
    slug: "the-martian-2015",
    title: "The Martian (2015)",
    image: "https://image.tmdb.org/t/p/w500/5BHuvQ6p9kfc091Z8RiFNhCwL4b.jpg",
    shortDescription: "An astronaut is stranded on Mars and fights to survive.",
    description: "Mark Watney uses science and determination to stay alive while NASA and his crew attempt a rescue.",
    category: "Sci-Fi",
    level: "Intermediate",
    duration: "2h 24m",
    imdbRating: 8.0,
    language: "English / Mandarin",
    country: "United States / United Kingdom / Hungary / Jordan",
    boxOffice: "$631M worldwide",
    instructorSlug: "ridley-scott",
    lessons: ["Matt Damon", "Jessica Chastain", "Kristen Wiig", "Jeff Daniels", "Chiwetel Ejiofor"],
  },
  {
    id: "c36",
    slug: "the-terminator-1984",
    title: "The Terminator (1984)",
    image: "https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
    shortDescription: "A cyborg assassin is sent from the future to kill Sarah Connor.",
    description: "Sarah Connor becomes the target of a machine from the future while a soldier tries to protect her.",
    category: "Sci-Fi",
    level: "Intermediate",
    duration: "1h 47m",
    imdbRating: 8.1,
    language: "English / Spanish",
    country: "United Kingdom / United States",
    boxOffice: "$78M worldwide",
    instructorSlug: "james-cameron",
    lessons: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn", "Paul Winfield", "Lance Henriksen"],
  },
  {
    id: "c37",
    slug: "aliens-1986",
    title: "Aliens (1986)",
    image: "https://image.tmdb.org/t/p/w500/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg",
    shortDescription: "Ripley returns to face the alien threat with space marines.",
    description: "Ellen Ripley joins a military mission to investigate a colony overrun by deadly creatures.",
    category: "Sci-Fi",
    level: "Advanced",
    duration: "2h 17m",
    imdbRating: 8.4,
    language: "English",
    country: "United Kingdom / United States",
    boxOffice: "$183M worldwide",
    instructorSlug: "james-cameron",
    lessons: ["Sigourney Weaver", "Michael Biehn", "Carrie Henn", "Paul Reiser", "Bill Paxton"],
  },
  {
    id: "c38",
    slug: "terminator-2-judgment-day-1991",
    title: "Terminator 2: Judgment Day (1991)",
    image: "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
    shortDescription: "A reprogrammed Terminator protects John Connor from a new threat.",
    description: "A more advanced machine is sent to kill John Connor while an older Terminator becomes his protector.",
    category: "Action",
    level: "Intermediate",
    duration: "2h 17m",
    imdbRating: 8.6,
    language: "English / Spanish",
    country: "United States / France",
    boxOffice: "$521M worldwide",
    instructorSlug: "james-cameron",
    lessons: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick", "Joe Morton"],
  },
  {
    id: "c39",
    slug: "titanic-1997",
    title: "Titanic (1997)",
    image: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    shortDescription: "A romance unfolds aboard the doomed RMS Titanic.",
    description: "Jack and Rose fall in love during the Titanic's maiden voyage, while class divisions and disaster shape their fate.",
    category: "Drama",
    level: "Beginner",
    duration: "3h 14m",
    imdbRating: 7.9,
    language: "English / Swedish / Italian / French",
    country: "United States / Mexico",
    boxOffice: "$2.264B worldwide",
    instructorSlug: "james-cameron",
    lessons: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates", "Frances Fisher"],
  },
  {
    id: "c40",
    slug: "avatar-2009",
    title: "Avatar (2009)",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    shortDescription: "A marine becomes part of an alien world and its conflict.",
    description: "Jake Sully enters the world of Pandora and becomes torn between a military mission and the Na'vi people.",
    category: "Sci-Fi",
    level: "Intermediate",
    duration: "2h 42m",
    imdbRating: 7.9,
    language: "English / Spanish",
    country: "United States",
    boxOffice: "$2.923B worldwide",
    instructorSlug: "james-cameron",
    lessons: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver", "Stephen Lang", "Michelle Rodriguez"],
  },
  {
    id: "c41",
    slug: "the-lord-of-the-rings-the-fellowship-of-the-ring-2001",
    title: "The Lord of the Rings: The Fellowship of the Ring (2001)",
    image: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    shortDescription: "A hobbit begins a dangerous quest to destroy a powerful ring.",
    description: "Frodo and his companions set out from the Shire to protect Middle-earth from the Dark Lord Sauron.",
    category: "Fantasy",
    level: "Intermediate",
    duration: "2h 58m",
    imdbRating: 8.9,
    language: "English / Sindarin",
    country: "New Zealand / United States",
    boxOffice: "$898M worldwide",
    instructorSlug: "peter-jackson",
    lessons: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Orlando Bloom"],
  },
  {
    id: "c42",
    slug: "the-lord-of-the-rings-the-two-towers-2002",
    title: "The Lord of the Rings: The Two Towers (2002)",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    shortDescription: "The fellowship is divided as war rises across Middle-earth.",
    description: "Frodo and Sam continue toward Mordor while Aragorn, Legolas, and Gimli prepare for war.",
    category: "Fantasy",
    level: "Intermediate",
    duration: "2h 59m",
    imdbRating: 8.8,
    language: "English / Sindarin / Old English",
    country: "New Zealand / United States",
    boxOffice: "$948M worldwide",
    instructorSlug: "peter-jackson",
    lessons: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Andy Serkis"],
  },
  {
    id: "c43",
    slug: "the-lord-of-the-rings-the-return-of-the-king-2003",
    title: "The Lord of the Rings: The Return of the King (2003)",
    image: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    shortDescription: "The final battle for Middle-earth begins.",
    description: "Frodo approaches Mount Doom as kingdoms unite for one final stand against Sauron.",
    category: "Fantasy",
    level: "Advanced",
    duration: "3h 21m",
    imdbRating: 9.0,
    language: "English / Quenya / Old English / Sindarin",
    country: "New Zealand / United States",
    boxOffice: "$1.147B worldwide",
    instructorSlug: "peter-jackson",
    lessons: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin", "Andy Serkis"],
  },
  {
    id: "c44",
    slug: "king-kong-2005",
    title: "King Kong (2005)",
    image: "https://image.tmdb.org/t/p/w500/6a2HY6UmD7XiDD3NokgaBAXEsD2.jpg",
    shortDescription: "A film crew discovers a giant ape on a mysterious island.",
    description: "A director leads a crew to Skull Island, where they encounter Kong and bring tragedy back to New York.",
    category: "Adventure",
    level: "Intermediate",
    duration: "3h 07m",
    imdbRating: 7.2,
    language: "English",
    country: "New Zealand / United States / Germany",
    boxOffice: "$557M worldwide",
    instructorSlug: "peter-jackson",
    lessons: ["Naomi Watts", "Jack Black", "Adrien Brody", "Thomas Kretschmann", "Andy Serkis"],
  },
  {
    id: "c45",
    slug: "the-hobbit-an-unexpected-journey-2012",
    title: "The Hobbit: An Unexpected Journey (2012)",
    image: "https://image.tmdb.org/t/p/w500/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg",
    shortDescription: "Bilbo Baggins joins dwarves on a quest to reclaim their homeland.",
    description: "Bilbo begins an unexpected adventure with Thorin and his company, encountering trolls, goblins, and Gollum.",
    category: "Fantasy",
    level: "Beginner",
    duration: "2h 49m",
    imdbRating: 7.8,
    language: "English",
    country: "New Zealand / United States",
    boxOffice: "$1.017B worldwide",
    instructorSlug: "peter-jackson",
    lessons: ["Martin Freeman", "Ian McKellen", "Richard Armitage", "Andy Serkis", "Cate Blanchett"],
  },
  {
    id: "c46",
    slug: "the-godfather-1972",
    title: "The Godfather (1972)",
    image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    shortDescription: "The aging head of a crime family transfers power to his reluctant son.",
    description: "The Corleone family faces loyalty, violence, business, and power as Michael Corleone is drawn into the family empire.",
    category: "Crime",
    level: "Advanced",
    duration: "2h 55m",
    imdbRating: 9.2,
    language: "English / Italian / Latin",
    country: "United States",
    boxOffice: "$250M worldwide",
    instructorSlug: "francis-ford-coppola",
    lessons: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
  },
  {
    id: "c47",
    slug: "the-godfather-part-ii-1974",
    title: "The Godfather Part II (1974)",
    image: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    shortDescription: "Michael expands his power while Vito's early life is revealed.",
    description: "The sequel follows Michael Corleone's ruthless leadership and the young Vito Corleone's rise in New York.",
    category: "Crime",
    level: "Advanced",
    duration: "3h 22m",
    imdbRating: 9.0,
    language: "English / Italian / Spanish / Latin / Sicilian",
    country: "United States",
    boxOffice: "$48M worldwide",
    instructorSlug: "francis-ford-coppola",
    lessons: ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton", "John Cazale"],
  },
  {
    id: "c48",
    slug: "the-conversation-1974",
    title: "The Conversation (1974)",
    image: "https://image.tmdb.org/t/p/w600_and_h900_face/leZtiWJXHEp2x7jVW7djhcSboSJ.jpg",
    shortDescription: "A surveillance expert becomes obsessed with a recorded conversation.",
    description: "Harry Caul, a private surveillance expert, suspects that one of his recordings may lead to murder.",
    category: "Mystery",
    level: "Advanced",
    duration: "1h 53m",
    imdbRating: 7.7,
    language: "English",
    country: "United States",
    boxOffice: "$4.4M worldwide",
    instructorSlug: "francis-ford-coppola",
    lessons: ["Gene Hackman", "John Cazale", "Allen Garfield", "Frederic Forrest", "Cindy Williams"],
  },
  {
    id: "c49",
    slug: "apocalypse-now-1979",
    title: "Apocalypse Now (1979)",
    image: "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
    shortDescription: "A soldier travels upriver during the Vietnam War to find a rogue colonel.",
    description: "Captain Willard journeys through war and madness to confront Colonel Kurtz deep in the jungle.",
    category: "War",
    level: "Advanced",
    duration: "2h 27m",
    imdbRating: 8.4,
    language: "English / French / Vietnamese",
    country: "United States",
    boxOffice: "$105M worldwide",
    instructorSlug: "francis-ford-coppola",
    lessons: ["Martin Sheen", "Marlon Brando", "Robert Duvall", "Frederic Forrest", "Dennis Hopper"],
  },
  {
    id: "c50",
    slug: "bram-stokers-dracula-1992",
    title: "Bram Stoker's Dracula (1992)",
    image: "https://image.tmdb.org/t/p/w500/scFDS0U5uYAjcVTyjNc7GmcZw1q.jpg",
    shortDescription: "Dracula travels to London in search of lost love and new victims.",
    description: "A gothic romance and horror story about Dracula, Mina, obsession, immortality, and desire.",
    category: "Horror",
    level: "Intermediate",
    duration: "2h 08m",
    imdbRating: 7.4,
    language: "English / Romanian / Greek / Bulgarian / Latin",
    country: "United States / United Kingdom / Romania",
    boxOffice: "$216M worldwide",
    instructorSlug: "francis-ford-coppola",
    lessons: ["Gary Oldman", "Winona Ryder", "Anthony Hopkins", "Keanu Reeves", "Sadie Frost"],
  },
];

export function getAllCourses(): Course[] {
  return courses;
}

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug);
}

export function getAllInstructors(): Instructor[] {
  return instructors;
}

export function getInstructorBySlug(slug: string): Instructor | undefined {
  return instructors.find((i) => i.slug === slug);
}

export function getCoursesByInstructor(instructorSlug: string): Course[] {
  return courses.filter((c) => c.instructorSlug === instructorSlug);
}

export function getCourseCategories(): string[] {
  return Array.from(new Set(courses.map((c) => c.category))).sort();
}

export function getCourseLevels(): string[] {
  return Array.from(new Set(courses.map((c) => c.level)));
}

export function getCourseRatings(): number[] {
  return Array.from(new Set(courses.map((c) => c.imdbRating))).sort((a, b) => b - a);
}

export function getCourseLanguages(): string[] {
  return Array.from(new Set(courses.map((c) => c.language))).sort();
}

export function getCourseCountries(): string[] {
  return Array.from(new Set(courses.map((c) => c.country))).sort();
}